# Generated by Django 4.1.2 on 2023-05-06 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('bom_id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('artifact', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hardcoded_Creds',
            fields=[
                ('cred_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_location', models.CharField(max_length=200)),
                ('line_of_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_directory', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
                ('group_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerabilities',
            fields=[
                ('vuln_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('file_location', models.CharField(max_length=200)),
                ('line_of_code', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=50)),
                ('cve_id', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('suggested_fix', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=50)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scans_api.teams')),
            ],
        ),
        migrations.CreateModel(
            name='Scans',
            fields=[
                ('scan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bom', models.ManyToManyField(blank=True, to='scans_api.bom')),
                ('hardcoded_creds', models.ManyToManyField(blank=True, to='scans_api.hardcoded_creds')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scans_api.projects')),
                ('vulnerabilities', models.ManyToManyField(blank=True, to='scans_api.vulnerabilities')),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='assigned_team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scans_api.teams'),
        ),
    ]
