# Generated by Django 4.2.1 on 2023-05-08 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("scans_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="assigned_team_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scans_api.teams",
            ),
        ),
    ]
